baseURL = 'https://theia-cloud.io/'
languageCode = 'en-us'
title = 'Theia Cloud - running Theia-based products in the cloud'
theme = "syna"

[outputs]
  home = ["HTML", "JSON"]

[markup.goldmark.renderer]
  unsafe= true

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[params]
  name = "EclipseSource"
  description = "Theia Cloud"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    #favicon_svg = "favicon.svg"

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#00838F"
    secondary = "#868e96"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = ""
  name = "Home"
  weight = 10

[[menu.main]]
  url = "support"
  name = "Support"
  weight = 20

[[menu.main]]
  url = "documentation"
  name = "Documentation"
  weight = 25

# [[menu.main]]
#   url = "examples"
#   name = "Examples"
#   weight = 30

# [[menu.main]]
#   url = "gallery"
#   name = "Gallery"
#   weight = 40

[[menu.main]]
  url = "contact"
  name = "Contact"
  weight = 60

[[menu.main]]
  url = "https://github.com/eclipsesource/theia-cloud"
  name = "GitHub"
  weight = 60

[[menu.footer]]
  url = "https://eclipsesource.com/technology/eclipse-theia"
  name = "Eclipse Theia IDE"
  weight = 10

[[menu.footer]]
  url = "https://projects.eclipse.org/projects/ecd.cdt-cloud"
  name = "Eclipse CDT.cloud"
  weight = 20

[[menu.footer]]
  url = "https://projects.eclipse.org/projects/ecd.emfcloud"
  name = "Eclipse EMF.cloud"
  weight = 30

[[menu.footer]]
  url = "https://eclipse.org/che"
  name = "Eclipse Che"
  weight = 40

[[menu.copyright_footer]]
  url = "https://eclipsesource.com/about/company/"
  name = "About"
  weight = 5

[[menu.copyright_footer]]
  url = "https://eclipsesource.com/privacy/"
  name = "Privacy Policy"
  weight = 10

[[menu.copyright_footer]]
  url = "https://eclipsesource.com/terms-of-use/"
  name = "Terms of Use"
  weight = 20

# [[menu.copyright_footer]]
#   url = "https://www.eclipse.org/legal/copyright.php"
#   name = "Copyright"
#   weight = 30

[[menu.copyright_footer]]
  url = "https://eclipsesource.com/imprint/"
  name = "Legal"
  weight = 40

[[menu.footer_social]]
  weight = 20
  name = "twitter"
  pre = "fab fa-twitter"
  url = "https://twitter.com/eclipsesource"

[[menu.footer_social]]
  weight = 30
  name = "github"
  pre = "fab fa-github"
  url = "https://github.com/eclipsesource/theia-cloud"

[[menu.footer_social]]
  weight = 30
  name = "github-discussions"
  pre = "far fa-comments"
  url = "https://github.com/eclipsesource/theia-cloud/discussions"
