[build]
publish = "public"
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.production.environment]
HUGO_VERSION = "0.78.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.78.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.78.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.78.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://theia-cloud.io"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "base-uri 'self' main--theia-cloud.netlify.app *.theia-cloud.io; default-src 'self' 'unsafe-inline' main--theia-cloud.netlify.app *.theia-cloud.io https://unpkg.com https://*.iubenda.com https://cdnjs.cloudflare.com https://www.googletagmanager.com https://*.google-analytics.com https://storage.googleapis.com; style-src 'self' 'unsafe-inline' main--theia-cloud.netlify.app *.theia-cloud.io https://fonts.googleapis.com https://cdn.iubenda.com; img-src 'self' main--theia-cloud.netlify.app *.theia-cloud.io data: https://www.googletagmanager.com; font-src 'self' main--theia-cloud.netlify.app *.theia-cloud.io data: https://fonts.gstatic.com"
